### ISSUE TITLE
Courses should be more manageable by instructors

### ISSUE THREAD

**Issue by lenglund** [ubc/compair#318]
- [x] Add delete option to non-LTI UI (needs to be enabled)
- [x] Add duplication option to non-LTI UI (needs to be enabled)
- [x] Enable deletion of courses (#389)
- [x] Add duplicate option to UI (#410 re-enabled for LTI course link)
- [x] Add duplication workflow to front end, once determined (partial #410)
- [x] Retest duplication from LTI (#410)
- [x] Add duplicate course API endpoint (#326)

**Comment by andrew-gardener** [comment]
#326 adds a working duplicate course endpoint

I realized that we also need a strategy for default answer periods for the duplicated assignments. Currently I'm setting answer and compare start/end dates to None which somewhat works for the front-end but isn't ideal

**Comment by xcompass** [comment]
Assuming instructors want to run the same assignment on the same week for each term. If the course has start date, we can calculate how many weeks into the course for each assignment. Then use the new course start date and number of weeks to calculate the new start date for assignment.

**Comment by lenglund** [comment]
Need to think about where to put delete option for course. Should consider how duplication workflow works. This where we can deal with shifting dates for each year.

**Comment by andrew-gardener** [comment]
#410 adds assignments to course duplicate feature. 

It lists the assignment name, answer start/end dates, and compare start/end dates. All start and ends dates will be automatically adjusted to the current week by default. The automatically generated start/end times are based on difference in weeks so dates will fall on the same weekdays and maintain the same rough time distance from the beginning of the course (ex: an assignment will stay on 'week 2 Monday').

If the 'Adjust Assignment Dates' button is pressed, all assignment start/end dates will be automatically adjusted to the new course start date. When the button is pressed, any manual changes to the assignment dates will also be lost (including adding/removing a compare periods).

@lenglund the UI of the assignments of the form defiantly needs to be looked over (I just threw something together).

**Comment by lenglund** [comment]
Updates to include #290.

**Comment by lenglund** [comment]
@andrew-gardener, can you complete "to dos" for branch 0.9.x-Continue-#318? For home page:

- [ ] Enable duplication of courses
- [ ] Count/display total assignments for each course 
- [ ] Count/display total unfinished assignments for each course for individual students
- [ ] Count/display total users for each course
- [ ] Enable deletion of courses

I can revisit after...

**Comment by andrew-gardener** [comment]
@lenglund to dos completed in #440

**Comment by lenglund** [comment]
Awesome. Can you now review 3b7fc8fc02a87230314c6aa87181d439d81f2ab4 and hook course name to the back end? I think we can close this issue after that...
