### ISSUE TITLE
Temporary tracking of issues in testing

### ISSUE THREAD

**Issue by lenglund** [ubc/compair#473]
@andrew-gardener, feel free to mark off, comment on, edit, delete

Answering:
- [x] Simply accessing answer screen creates draft (turns Answer button into Finish Answering, removes "Submit As" select) (2e5a93bee21fd4acbd7364014d1338adf8d5bbf5)
- [x] Answer *draft* should also allow submit when only a file is attached (since this counts as an answer), works for initial answer and also if answer draft attachment is removed and re-added (3684adaf275321f42515e1416a875fd6069cbfef)

Assignments:
- [x] Instructor should be able to edit default criteria when first creating assignment (this is what we implemented with #431, right? but edit link does not appear) (83895c86d4317dd9b8b3aac72104714bfe799538)

Comparisons:
- [x] Dates/times no longer showing up on see comparisons screen? (79b49d5b0c0182fab336cc778da681f6cf543293)

Duplication:
- [x] Instructor answers duplicated when duplicating course and assignments (83895c86d4317dd9b8b3aac72104714bfe799538)

Manage Users:
- [x] Can we allow sorting by group? (79b49d5b0c0182fab336cc778da681f6cf543293)
- [x] Still not able to do an import (using Firefox), the button remains disabled despite a file being uploaded (caac60edb003e933303d0159571ada64ecfacf31)

 Participation Tab:
- [x] Need to remove ng-if="includeSelfEval" for th on the grade column on the participation tab to see this header (83895c86d4317dd9b8b3aac72104714bfe799538)
- [x] Need blank state for participation tab (don't show gradebook if no students enrolled, have message to explain) (ad0df736c27fd3a46409a792f54102550d600582)
- [x] Sorting by answer score does not work in participation tab (clicking on this header does not work, all other headers do) (79b49d5b0c0182fab336cc778da681f6cf543293)

Other:
- [x] Where more than PDF file attachments are allowed, text should reflect this (e.g., header becomes "Attachment (maximum size 25MB)" and text underneath becomes "Tip: Allowed file types include PDFs, MP3s, MP4s, JPGs, and PNGs. Try downloading <a href="https://get.adobe.com/reader/">Acrobat Reader</a> or using <a href="https://www.mozilla.org/en-US/firefox/new/">Firefox</a> or <a href="http://www.google.com/chrome/">Chrome</a> if you have problems uploading PDFs.") (3f76079f2f00b8782f0ca5dccce7b1564e03d139)
- [x] Chosen sprite not loading properly, so dropdown arrows not displaying for Chosen selects (71582081565f37c4319fdcdc668a7c9a5805330e)

**Comment by andrew-gardener** [comment]
@lenglund Please review ad0df736c27fd3a46409a792f54102550d600582 (grade book blank slate) and modify message if needed

**Comment by lenglund** [comment]
- [ ] Chosen no longer being applied to dropdowns?

**Comment by lenglund** [comment]
- [ ] Instructors should be able to save drafts (unless there is a reason we're not letting them?)

**Comment by andrew-gardener** [comment]
https://github.com/ubc/compair/issues/473#issuecomment-266848872 I believe we decided at the time that only students would need to be able to save drafts. It would also make the "submit as" logic a bit more complicated (ex: should instructors be able to save drafts on behalf of a student).

Always, if we want this, I'd suggest to remove option to save as draft if instructor/ta selects anyone else besides themselves from the submit as list. When they are selected we can enable saving as draft (that way we avoid any weird states)

**Comment by lenglund** [comment]
Good point and definitely we'd want to keep this to just submitting as themselves. Alternatively, I'm fine just removing the instructional text that says you can save this answer from the instructor/TA view.

**Comment by lenglund** [comment]
- [ ] Display courses on home page by start date (or, if no start date, first assignment start date)?

**Comment by lenglund** [comment]
- [ ] Home page should only list total number of assignments the user can see for each course (so instructor/TA should see total, but students only see total that are *after* the start date)

**Comment by lenglund** [comment]
- [ ] Allow admin to edit own course role
