### ISSUE TITLE
Enhance learning analytics

### ISSUE THREAD

**Issue by andrew-gardener** [ubc/compair#522]
- [ ] ~~Handle media playback related to #521~~
- [x] Better failure handling when sending records to LRS (22188ec340c60f16dc6d92d337c0ff25c27dbfc3)
- [x] Consider Caliper instead of xAPI (#790)
- [x] Add Group tracking (#783)
- [x] Consider additional trackables
- [x] Revise how uuids are generated and tracked when answering/comparing (drafts created on page load is less than desirable)

**Comment by lenglund** [comment]
On hold with #466 until decisions are made re: learning analytics at UBC.
